app:
  appname: edrops
server:
  error:
    include-stacktrace: always
    include-exception: true
  #only embedded Tomcat setting, ignored if war file is deployed to tomcat
  port: 8080
#  port: 8443
spring:
  main:
    banner-mode: off

  messages:
    basename: language/messages
    fallback-to-system-locale: true
    encoding: UTF-8
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
# Must be investigated. Should really be set to false.
    open-in-view: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
#   url: jdbc:h2:file:/data/mydb1
    username: sa
    password: sa
  # Required for development instant change
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
  web:
    resources:
 #     static-locations: file:src/main/resources/static/
      cache:
        period: 0
  devtools:
    livereload.enabled: true
---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      properties:
        hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: h2disk
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:file:C:/h2/edrops
    username: sa
    password: sa
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: mariadb
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: mariadocker
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

