app:
  appname: edrops

spring:
  main:
    banner-mode: off
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
#   url: jdbc:h2:file:/data/mydb1
    username: sa
    password: sa
  h2:
    console.enabled: true
  # Required for development instant change
  thymeleaf:
    cache: false
    enabled: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      properties:
        hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console.enabled: true

