app:
  appname: edrops

hibernate:
  connection:
    driver_class: org.h2.Driver
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1
    username: sa
    autocommit: true
    jdbc.password:

  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  hbm2ddl.auto: create-drop

---
spring:
  config:
    activate:
      on-profile: h2

  connection:
    driver_class: org.h2.Driver
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1
    username: sa
    autocommit: true
    jdbc.password: