app:
  appname: ${APP_NAME:edrops}
  user: Reier
  password: $2a$10$RXI.HV1eFSTCsHlDFFkHlO37yjw4qM4XS6I57gP2upV46lDi0ZFTa
  auth: true
server:
  error:
    include-stacktrace: always
    include-exception: true
    whitelabel.enabled: false
    path: /error
  #absolutely required to avoid tomcat picking up error before Spring error handling
  tomcat:
    relaxed-path-chars: \,{,},|,^,`
    relaxed-query-chars: \,{,},|,^,`
  #only embedded Tomcat setting, ignored if war file is deployed to tomcat
  port: 8080
#  port: 8443
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.apache.coyote.http11: INFO
    com.techreier.edrops: INFO
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd' 'HH:mm:ss.SS, UTC} [%thread] %-5level %logger{36} - %msg%n"
spring:
  profiles:
    active: h2-prod
#  threads.virtual.enabled: true
  main:
    banner-mode: off
  messages:
    basename: language/messages
    fallback-to-system-locale: true
    encoding: UTF-8
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
# Must be investigated. Should really be set to false.
    open-in-view: false
    properties:
      hibernate.show_sql: false
      hibernate.jdbc.time_zone: UTC
  datasource:
#    url: jdbc:mariadb://host.docker.internal:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
#    username: dbuser
#    password: PerSeter33
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa

# cache false and period 0 required for development instant change
  thymeleaf:
    cache: true
    enabled: true
    encoding: UTF-8
    mode: HTML
  web.resources.cache.period: 3600

---
spring:
  config:
    activate:
      on-profile: h2-jpa-generate
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: com.techreier.edrops.config.MyImplicitNamingStrategy
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa
  thymeleaf:
    cache: false
  devtools:
    livereload.enabled: true
  web.resources.cache.period: 3600
  h2:
    console.enabled: true
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.apache.coyote.http11: INFO
    com.techreier.edrops: INFO
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.SQL: INFO
---
spring:
  config:
    activate:
      on-profile: h2
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa
  thymeleaf:
    cache: false
  devtools:
    livereload.enabled: true
    restart.enabled: true
  web.resources.cache.period: 3600
  h2:
    console.enabled: true
app:
  auth: false
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.apache.coyote.http11: INFO
    com.techreier.edrops: INFO
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.SQL: INFO
---
spring:
  config:
    activate:
      on-profile: h2-prod
  flyway:
      enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password: sa
  thymeleaf:
    cache: true
  devtools:
    livereload.enabled: false
  web.resources.cache.period: 3600
  h2:
    console.enabled: false

---
spring:
  config:
    activate:
      on-profile: h2-disk
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:h2:file:C:/h2/edrops;MODE=MYSQL
    username: sa
    password: sa
  thymeleaf.cache: true
  web.resources.cache.period: 3600
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: local-mariadb
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:mariadb://localhost:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: docker-mariadb
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
#   url: jdbc:mariadb://192.168.2.107:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mariadb://host.docker.internal:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}
  thymeleaf.cache: true
  web.resources.cache.period: 3600
---
spring:
  config:
    activate:
      on-profile: mariadb-dockerized
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:mariadb://host.docker.internal:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}
  thymeleaf.cache: true
  web.resources.cache.period: 3600

---
spring:
  config:
    activate:
      on-profile: global-mariadb
  flyway:
    enabled: true
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate.show_sql: false
  datasource:
    url: jdbc:mariadb://mdb:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}
  thymeleaf.cache: true
  web.resources.cache.period: 3600

