app:
  appname: edrops

spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
      generate-ddl: true
  datasource:
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
