app:
  appname: ${APP_NAME:edrops}
server:
  error:
    include-stacktrace: always
    include-exception: true
    path: /error
  tomcat:
    relaxed-path-chars: \,{,},|,^,`
    relaxed-query-chars: \,{,},|,^,`
  error-pages:
    path: /error
  #only embedded Tomcat setting, ignored if war file is deployed to tomcat
  port: 8080
#  port: 8443
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.coyote.http11: INFO
    com.techreier.edrops: DEBUG
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
spring:
  profiles:
    active: h2
  main:
    banner-mode: off
# mvc:
#   static-locations used instead
#   why cannot wildcard be used here.
#   need to redefine default to pick up throw-exception...
#   static-path-pattern: "/css/**"
#   throw-exception-if-no-handler-found: true
  messages:
    basename: language/messages
    fallback-to-system-locale: true
    encoding: UTF-8
  jpa:
    generate-ddl: true
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
# Must be investigated. Should really be set to false.
    open-in-view: false
    properties:
      hibernate.show_sql: false

  datasource:
    url: jdbc:mariadb://host.docker.internal:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dbuser
    password: PerSeter33
    driverClassName: org.mariadb.jdbc.Driver

#  driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:mydb2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa

# Required for development instant change
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  devtools:
    livereload.enabled: true

---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      properties:
        hibernate.show_sql: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: h2disk
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:/h2/edrops
    username: sa
    password: sa
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: local-mariadb
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: docker-mariadb
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
#   url: jdbc:mariadb://192.168.2.107:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mariadb://host.docker.internal:3307/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: mariadb-dockerized
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: global-mariadb
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mdb:3308/edrops?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dbuser
    password: ${DB_PASSWORD}

